version: "3.7"
services:
  db:
    image: library/postgres:13.1-alpine
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data13:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: "dpage/pgadmin4:4.28"
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@linuxhint.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - pgadmin28-data:/var/lib/pgadmin
    links:
      - "db:pgsql-server"
volumes:
  db-data13:
  pgadmin28-data:
